# NPTEL - 1

In [6]:
n = int(input())
arr = list(map(int, input().rstrip().split()))
print(arr)
rev_arr = arr[::-1] 
print(rev_arr)
new_arr = []
for i in range(n):
  new_arr.append(str(arr[i] + rev_arr[i]))
print(' '.join(new_arr))

4
1 2 3 4
[1, 2, 3, 4]
[4, 3, 2, 1]
5 5 5 5


In [7]:
for i in range(2): 
	print(i,end="") 

for i in range(4,6): 
	print(i,end="" )

0145

In [8]:
a=4.5
b=15
print(a+b)

19.5


In [9]:
i = 1
while True: 
	if i%3 == 0: 
		break
	print(i,end="") 
	i + = 1


SyntaxError: invalid syntax (<ipython-input-9-1f31ea621028>, line 6)

In [10]:
i = 2
while True:
    if i%3 == 0:
        break
    print(i,end="")
    i += 2

24

In [11]:
print(3*1**3)

3


In [12]:
x=4.5
y=int(x)
print(y)

4


In [1]:
numbers = [1, 2, 3, 4]
numbers.append([5,6,7,8])
print(len(numbers))

5


In [3]:
list1 = [1, 3]
list2 = list1
list1[0] = 4
print(list2)

[4, 3]


In [8]:
import random
print(random.randrange(1,100,10))

81


In [13]:
list = [55, 66, 77, 88, 99]
print(random.choice(list))

55


In [15]:
import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [1, 2, 3, 4, 5]
plt.plot(x,y)
plt.show()

<Figure size 640x480 with 1 Axes>

In [10]:
arr = list(map(int, input().rstrip().split()))
arr.sort()
print(arr[-2], arr[1])

1 3 2 5 4
4 2


In [23]:
numbers = input()
list = numbers.split()
print(list)
newList = [item for item in list if int(item)%5!=0]
print(' '.join(newList))

2 3 4 5 6
['2', '3', '4', '5', '6']
2 3 4 6


In [27]:
inp = input()
one = 0
for i in range(0, len(inp)):
    if int(inp[i]) == 1:
       one+=1
if len(inp) - one == 1:
    print('YES')
else:
    print('NO')

0011
NO


In [1]:
A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print(A[1])

[4, 5, 6]


In [2]:
A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print([A[row][1] for row in (0, 1, 2)])

[2, 5, 8]


In [3]:
A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print([A[i][i] for i in range(len(A))])

[1, 5, 9]


In [6]:
n = int(input())
sum = 1
if n == 1:
    print(n)
else:
    for i in range(1, n+1):
        sum = sum * i
    print(sum)
        

6
720


In [14]:
import numpy as np
arr = list(map(int, input().rstrip().split()))
newarr = np.zeros( (arr[0], arr[1]) )
print(newarr)
num = 1
for i in range(0, arr[0]):
    for j in range(0, arr[1]):
        newarr[i][j] = int(num)
        num+=1
print(newarr)
        

2 3
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [41]:
r,c=map(int,input().split());
x=1
for i in range(r):
  for j in range(c-1):
    print(x,end=" ");
    x+=1
  print(x);
  x+=1;

2 3
1 2 3
4 5 6


In [3]:
#The number of swaps needed to sort the numbers [8, 22, 7, 9, 31, 5, 13] in ascending order, using bubble sort is

list1 = [2, 9, 5, 4, 8, 1]
cnt = 0
print(list1)
for j in range(len(list1)-1):
    print(list1)
    for i in range(len(list1)-1-j):
        if list1[i] > list1[i+1]:
            list1[i],list1[i+1] = list1[i+1], list1[i]
            cnt+=1
print(list1)
print(cnt)

[2, 9, 5, 4, 8, 1]
[2, 9, 5, 4, 8, 1]
[2, 5, 4, 8, 1, 9]
[2, 4, 5, 1, 8, 9]
[2, 4, 1, 5, 8, 9]
[2, 1, 4, 5, 8, 9]
[1, 2, 4, 5, 8, 9]
9


In [11]:
def digital_sum(n):
    if n <0:
        return digital_sum(-n)
    elif n == 0:
        return 0
    else:
        print(n%10)
        print(n//10)
        return n%10 + digital_sum(n//10)

digital_sum(123)

3
12
2
1
1
0


6